export {
  buildGatewayDefaultName,
  getGatewayBackendCapabilities,
  getGatewayBackendDescriptor,
  getGatewayModeLabel,
  getGatewayThinkingLevels,
  isGatewayBackendKind,
  isGatewayTransportKind,
  resolveGatewayBackendKind,
  resolveGatewayTransportKind,
  resolveGlobalMainSessionKey,
  selectByBackend,
  toGatewayConfigIdentity,
  toLegacyGatewayMode,
  type GatewayBackendCapabilities,
  type GatewayBackendDescriptor,
} from '@clawket/agent-protocol';
