/** Clawket-owned compatibility for legacy and split Hermes skill modules. */
export const HERMES_SKILLS_COMPAT_PYTHON = [
  'import inspect',
  'import agent.skill_utils as _skill_utils',
  'import tools.skills_tool as _skills_tool',
  'from tools.skills_tool import SKILLS_DIR, load_env',
  '_parse_frontmatter = getattr(_skill_utils, "parse_frontmatter", None) or getattr(_skills_tool, "_parse_frontmatter")',
  'skill_matches_platform = getattr(_skill_utils, "skill_matches_platform", None) or getattr(_skills_tool, "skill_matches_platform")',
  'def _collect_prerequisite_values(frontmatter):',
  '  legacy = getattr(_skills_tool, "_collect_prerequisite_values", None)',
  '  if legacy is not None:',
  '    return legacy(frontmatter)',
  '  prereqs = frontmatter.get("prerequisites")',
  '  if not isinstance(prereqs, dict):',
  '    return [], []',
  '  def values(raw):',
  '    raw = [raw] if isinstance(raw, str) else raw if isinstance(raw, list) else []',
  '    return [str(value).strip() for value in raw if str(value).strip()]',
  '  return values(prereqs.get("env_vars")), values(prereqs.get("commands"))',
  'def _get_required_environment_variables(frontmatter, legacy_env):',
  '  resolve = _skills_tool._get_required_environment_variables',
  '  if len(inspect.signature(resolve).parameters) >= 2:',
  '    return resolve(frontmatter, legacy_env)',
  '  return resolve(frontmatter)',
] as const;
