import { expect, it } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { CodexService } from './service.js';
import { inspectCodexInstallation } from './executable.js';

it('runs real installed Codex conversations, native branches, interruption and durable recovery', async () => {
  if (process.env.CLAWKET_CODEX_LIVE !== '1') throw new Error('Set CLAWKET_CODEX_LIVE=1 with an authenticated Codex installation. This test uses real model access.');
  const command = process.env.CLAWKET_CODEX_COMMAND ?? 'codex';
  const { version } = await inspectCodexInstallation(command);
  const root = mkdtempSync(join(tmpdir(), 'clawket-codex-live-')), project = join(root, 'project'), directory = join(root, 'state');
  mkdirSync(project);
  let service = new CodexService({ project, directory, command });
  const events: any[] = []; service.on('update', e => events.push(e));
  const request = (method: string, params: object = {}) => service.request({ type: 'req', id: randomUUID(), method, params }) as Promise<any>;
  const wait = async (predicate: () => boolean, timeout = 90000) => { const end = Date.now() + timeout; while (!predicate()) { if (Date.now() > end) throw Error('Real Codex condition timed out'); await new Promise(r => setTimeout(r, 100)); } };
  try {
    expect(await service.health()).toMatchObject({ backend: 'codex', modelReady: true });
    const key = (await request('sessions.create')).key;
    const selection = await request('models.list', { sessionKey: key });
    expect(selection.models.length).toBeGreaterThan(0);
    expect((await request('chat.history', { sessionKey: key })).messages).toEqual([]);
    await service.stop(); service = new CodexService({ project, directory, command });
    service.on('update', e => events.push(e));
    await request('models.list', { sessionKey: key });
    const nativeModel = selection.models.find((m: any) => m.id === selection.currentModel);
    const effort = nativeModel?.reasoningLevels?.includes('low') ? 'low' : nativeModel?.reasoningLevels?.[0];
    if (effort) expect((await request('models.thinking', { sessionKey: key, level: effort })).thinkingLevel).toBe(effort);
    await service.stop(); service = new CodexService({ project, directory, command });
    service.on('update', e => events.push(e));
    await request('sessions.rename', { sessionKey: key, title: 'Restored empty session' });
    if (effort) expect((await request('models.list', { sessionKey: key })).thinkingLevel).toBe(effort);
    const input = { sessionKey: key, text: 'Reply exactly LIVE_CODEX_OK. Do not use tools.', idempotencyKey: randomUUID() };
    const started = Date.now(), first = await request('chat.send', input);
    expect(await request('chat.send', input)).toEqual(first);
    await wait(() => events.some(e => e.type === 'run_finished' && e.runId === first.runId));
    let history = await request('chat.history', { sessionKey: key });
    expect(history.messages.some((m: any) => m.role === 'assistant' && m.text.includes('LIVE_CODEX_OK'))).toBe(true);
    const branch = await request('sessions.create', { fromSession: key, title: 'Native branch' });
    expect((await request('chat.history', { sessionKey: branch.key })).messages.some((m: any) => m.text.includes('LIVE_CODEX_OK'))).toBe(true);
    await request('sessions.rename', { sessionKey: branch.key, title: 'Renamed branch' });
    expect((await request('sessions.list')).find((s: any) => s.key === branch.key).title).toBe('Renamed branch');
    await request('sessions.reset', { sessionKey: branch.key });
    expect((await request('chat.history', { sessionKey: branch.key })).messages).toEqual([]);
    await request('sessions.delete', { sessionKey: branch.key });
    expect((await request('sessions.list')).some((s: any) => s.key === branch.key)).toBe(false);
    const steerable = await request('chat.send', { sessionKey: key, text: 'Execute the shell command sleep 5; printf STEER_WAIT. Use the command tool now. After it completes reply WAIT_DONE.', idempotencyKey: randomUUID() });
    await wait(() => events.some(e => e.type === 'tool_call' && e.runId === steerable.runId));
    await request('chat.steer', { sessionKey: key, runId: steerable.runId, text: 'Your new final answer must be exactly STEERED_CODEX_OK. No further tools.' });
    await wait(() => events.some(e => e.type === 'run_finished' && e.runId === steerable.runId));
    expect((await request('chat.history', { sessionKey: key })).messages.some((m: any) => m.role === 'assistant' && m.text.includes('STEERED_CODEX_OK'))).toBe(true);
    const slow = await request('chat.send', { sessionKey: key, text: 'Run the shell command sleep 30; printf SLEEP_DONE. Use the command tool now and wait for its result.', idempotencyKey: randomUUID() });
    await wait(() => events.some(e => e.type === 'tool_call' && e.runId === slow.runId));
    await request('chat.abort', { sessionKey: key, runId: slow.runId });
    await wait(() => events.some(e => e.type === 'run_finished' && e.runId === slow.runId));
    expect(events.find(e => e.type === 'run_finished' && e.runId === slow.runId).stopReason).toBe('cancelled');
    await service.stop(); service = new CodexService({ project, directory, command });
    history = await request('chat.history', { sessionKey: key });
    expect(history.hasActiveRun).toBe(false);
    expect(history.messages.some((m: any) => m.text.includes('LIVE_CODEX_OK'))).toBe(true);
    if (effort) expect((await request('models.list', { sessionKey: key })).thinkingLevel).toBe(effort);
    expect(await request('chat.send', input)).toEqual(first);
    await request('sessions.reset', { sessionKey: key });
    console.log(`Verified ${version}: model catalog, empty history, text, idempotency, branch/history, rename/reset/delete, native steering, reasoning, interrupt and restart (${Date.now() - started} ms).`);
  } catch (error) {
    console.error('Live test events:', events.map(e => ({ type: e.type, stopReason: e.stopReason, title: e.question?.title, text: e.type === 'run_finished' ? e.message?.content : undefined })));
    throw error;
  } finally { await service.stop(); rmSync(root, { recursive: true, force: true }); }
}, 180000);
