import { afterEach, expect, it } from 'vitest';
import { createServer, type Server } from 'node:http';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import WebSocket from 'ws';
import { PiService } from './service.js';
import { PiServer } from './server.js';

const cleanup: Array<() => Promise<void> | void> = [];
afterEach(async () => { for (const fn of cleanup.reverse()) await fn(); cleanup.length = 0; });
async function waitFor(test: () => boolean, timeout = 15000): Promise<void> {
  const end = Date.now() + timeout;
  while (!test()) { if (Date.now() > end) throw new Error('Timed out waiting for Pi evidence'); await new Promise(r => setTimeout(r, 20)); }
}

it('runs installed Pi through the authenticated Bridge: tools, dialogs, models, recovery, duplicate protection and native branches', async () => {
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'clawket-pi-integration-')));
  cleanup.push(() => rmSync(root, { recursive: true, force: true }));
  const project = join(root, 'project'), agentDirectory = join(root, 'agent'), directory = join(root, 'bridge');
  mkdirSync(project); mkdirSync(agentDirectory); writeFileSync(join(project, 'sample.txt'), 'REAL_PI_READ_OK');
  let modelRequests = 0; const receivedPrompts: string[] = [];
  const modelServer: Server = createServer(async (req, res) => {
    let body = ''; for await (const chunk of req) body += chunk;
    const input = JSON.parse(body); modelRequests++;
    const messages = input.messages, user = messages.filter((m: any) => m.role === 'user').at(-1)?.content ?? '';
    receivedPrompts.push(JSON.stringify(user));
    res.writeHead(200, { 'Content-Type': 'text/event-stream' });
    const chunk = (delta: object, finish: string | null = null) => res.write(`data: ${JSON.stringify({ id: 'test', object: 'chat.completion.chunk', created: 1, model: input.model, choices: [{ index: 0, delta, finish_reason: finish }] })}\n\n`);
    chunk({ role: 'assistant', content: '' });
    if (JSON.stringify(user).includes('READ_SAMPLE') && messages.at(-1).role !== 'tool') {
      chunk({ tool_calls: [{ index: 0, id: 'test-read', type: 'function', function: { name: 'read', arguments: '{"path":"sample.txt"}' } }] }); chunk({}, 'tool_calls');
    } else {
      chunk({ content: 'Pi ' });
      if (JSON.stringify(user).includes('SLOW')) await new Promise(r => setTimeout(r, 1000));
      chunk({ content: 'answer\u2028OK' }); chunk({}, 'stop');
    }
    res.end('data: [DONE]\n\n');
  });
  await new Promise<void>(r => modelServer.listen(0, '127.0.0.1', r));
  cleanup.push(() => new Promise<void>(r => { modelServer.closeAllConnections(); modelServer.close(() => r()); }));
  const port = (modelServer.address() as { port: number }).port;
  writeFileSync(join(agentDirectory, 'models.json'), JSON.stringify({ providers: { fixture: { baseUrl: `http://127.0.0.1:${port}/v1`, api: 'openai-completions', apiKey: 'fixture-only', models: [{ id: 'one', input: ['text', 'image'], contextWindow: 8192, maxTokens: 1024 }, { id: 'two', contextWindow: 8192, maxTokens: 1024 }] } } }));
  const extension = join(root, 'question.ts');
  writeFileSync(extension, `export default function(pi) { pi.registerCommand('question', { handler: async (_args, ctx) => { const answer = await ctx.ui.confirm('Fixture question', 'Continue?'); ctx.ui.notify(answer ? 'CONFIRMED' : 'DECLINED', 'info'); } }); }`);
  const skill = join(root, 'SKILL.md');
  writeFileSync(skill, '---\nname: fixture-task\ndescription: Fixture task\n---\nSKILL_MARKER');
  const options = { project, directory, agentDirectory, command: process.env.CLAWKET_PI_COMMAND ?? 'pi', args: ['--offline', '--no-approve', '--no-extensions', '--no-skills', '--no-prompt-templates', '--no-context-files', '--tools', 'read', '-e', extension, '--skill', skill, '--provider', 'fixture', '--model', 'one'] };
  let service = new PiService(options); cleanup.push(() => service.stop());
  const updates: any[] = []; service.on('update', event => updates.push(event));
  let sequence = 0;
  const rpc = (method: string, params: Record<string, unknown> = {}): Promise<any> => service.request({ type: 'req', id: String(++sequence), method, params });
  expect(await service.health()).toMatchObject({ backend: 'pi', model: 'one' });
  const sessions = await rpc('sessions.list'), key = sessions[0].key;
  const prompt = (text: string, idempotencyKey = text) => rpc('chat.send', { sessionKey: key, text, idempotencyKey });
  const settled = (runId: string) => waitFor(() => updates.some(e => e.type === 'run_finished' && e.runId === runId));
  const first = await prompt('READ_SAMPLE'); await settled(first.runId);
  expect(updates.some(e => e.type === 'tool_call' && e.title === 'read')).toBe(true);
  expect(updates.find(e => e.type === 'tool_call_update')?.rawOutput).toContain('REAL_PI_READ_OK');
  expect((await rpc('chat.history', { sessionKey: key })).messages.some((m: any) => m.text === 'Pi answer\u2028OK')).toBe(true);
  const requests = modelRequests;
  expect(await prompt('READ_SAMPLE')).toEqual(first); expect(modelRequests).toBe(requests);
  await expect(prompt('different', 'READ_SAMPLE')).rejects.toThrow('different content');
  const skills = await rpc('skills.list');
  expect(skills.skills).toEqual(expect.arrayContaining([expect.objectContaining({ name: 'fixture-task', invocation: '/skill:fixture-task ' })]));
  const skillRun = await prompt('/skill:fixture-task HELLO'); await settled(skillRun.runId);
  expect(receivedPrompts.at(-1)).toContain('SKILL_MARKER');
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC';
  const picture = await rpc('chat.send', { sessionKey: key, text: 'Image fixture', idempotencyKey: 'image', attachments: [{ type: 'image', mimeType: 'image/png', content: png }] });
  await settled(picture.runId);
  expect(receivedPrompts.at(-1)).toContain('image_url');
  expect((await rpc('chat.history', { sessionKey: key })).messages.some((m: any) => m.attachments?.[0]?.mimeType === 'image/png')).toBe(true);
  const guided = await prompt('SLOW_GUIDANCE');
  await waitFor(() => updates.some(e => e.runId === guided.runId && e.type === 'agent_message_chunk'));
  await rpc('chat.steer', { sessionKey: key, runId: guided.runId, text: 'GUIDANCE_TEXT' }); await settled(guided.runId);
  expect((await rpc('chat.history', { sessionKey: key })).messages.some((m: any) => m.role === 'user' && m.text.includes('GUIDANCE_TEXT'))).toBe(true);
  await rpc('models.select', { sessionKey: key, scope: 'session', provider: 'fixture', model: 'two' });
  expect((await rpc('models.list', { sessionKey: key })).currentModel).toBe('two');
  const second = await rpc('sessions.create', { title: 'Other task' });
  expect((await rpc('models.list', { sessionKey: second.key })).currentModel).toBe('one');
  await rpc('sessions.rename', { sessionKey: key, title: 'Named task' });
  expect((await rpc('sessions.list'))[0].title).toBe('Named task');
  const questionRun = await prompt('/question');
  await waitFor(() => updates.some(e => e.type === 'question_requested'));
  const pending = await rpc('questions.list', { sessionKey: key }); expect(pending).toHaveLength(1);
  await rpc('questions.respond', { sessionKey: key, questionId: pending[0].id, confirmed: true }); await settled(questionRun.runId);
  expect(updates.some(e => e.type === 'system_event' && e.text === 'CONFIRMED')).toBe(true);
  expect(await rpc('questions.list', { sessionKey: key })).toEqual([]);
  const cancelledQuestion = await prompt('/question', 'cancel-dialog');
  await waitFor(() => updates.filter(e => e.type === 'question_requested').length === 2);
  await rpc('chat.abort', { sessionKey: key, runId: cancelledQuestion.runId }); await settled(cancelledQuestion.runId);
  expect(updates.find(e => e.type === 'run_finished' && e.runId === cancelledQuestion.runId).stopReason).toBe('cancelled');
  expect(await rpc('questions.list', { sessionKey: key })).toEqual([]);
  const server = new PiServer(service, 'x'.repeat(64)); const bridgePort = await server.start(0);
  cleanup.push(() => server.stop());
  const socket = new WebSocket(`ws://127.0.0.1:${bridgePort}/v1/pi/ws`);
  await new Promise<void>(r => socket.once('open', r));
  const frames: any[] = []; socket.on('message', raw => frames.push(JSON.parse(raw.toString())));
  socket.send(JSON.stringify({ type: 'req', id: 'connect', method: 'connect', params: { token: 'x'.repeat(64) } }));
  await waitFor(() => frames.some(e => e.id === 'connect' && e.ok));
  const slow = await prompt('SLOW'); await waitFor(() => updates.some(e => e.runId === slow.runId && e.type === 'agent_message_chunk'));
  socket.close();
  expect((await rpc('chat.history', { sessionKey: key })).activeRun.runId).toBe(slow.runId);
  await rpc('chat.abort', { sessionKey: key, runId: slow.runId }); await settled(slow.runId);
  expect(updates.find(e => e.type === 'run_finished' && e.runId === slow.runId).stopReason).toBe('cancelled');
  const stored = JSON.parse(readFileSync(join(directory, 'sessions.json'), 'utf8'));
  const nativeDir = join(agentDirectory, 'sessions', `--${project.replace(/^[/\\]/, '').replace(/[/\\:]/g, '-')}--`); mkdirSync(nativeDir, { recursive: true });
  const nativeBytes = readFileSync(join(directory, stored.sessions[0].file), 'utf8'); writeFileSync(join(nativeDir, 'native.jsonl'), nativeBytes);
  const native = (await rpc('sessions.list')).find((s: any) => s.source === 'native'); expect(native.allowedActions.reset).toBe(false);
  await expect(rpc('chat.send', { sessionKey: native.key, text: 'no', idempotencyKey: 'native' })).rejects.toThrow('read-only');
  const branch = await rpc('sessions.create', { fromSession: native.key });
  expect((await rpc('chat.history', { sessionKey: branch.key })).messages.length).toBeGreaterThan(0);
  expect(readFileSync(join(nativeDir, 'native.jsonl'), 'utf8')).toBe(nativeBytes);
  await server.stop();
  service = new PiService({ ...options, args: options.args.slice(0, -4) });
  expect((await rpc('models.list', { sessionKey: key })).currentModel).toBe('two');
  expect((await rpc('chat.history', { sessionKey: key })).hasActiveRun).toBe(false);
  expect(await prompt('READ_SAMPLE')).toEqual(first);
  await rpc('sessions.reset', { sessionKey: second.key }); expect((await rpc('chat.history', { sessionKey: second.key })).messages).toEqual([]);
  await rpc('sessions.delete', { sessionKey: second.key }); expect((await rpc('sessions.list')).some((s: any) => s.key === second.key)).toBe(false);
  await expect(rpc('bash', { command: 'echo forbidden' })).rejects.toThrow('Unsupported');
}, 90000);
